# New gradle versions: https://github.com/FabricMC/fabric-example-mod

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# /- remove once modstitch has mixin config issue fixed and other stuff probably
org.gradle.configuration-cache=false

# Mod properties
mod.name=Chat Patches
mod.id=chatpatches
mod.group=dev.obro1961
mod.version=8.0-alpha.2
mod.author=OBro1961
mod.desc=A versatile client-side chat mod that makes the chat more useful and customizable! \
  Check out the GitHub page for more info, and join the Discord at https://discord.gg/3MqBvNEyMz!
mod.credits="FITFC (pt_br)","Calvineries (fr_fr)","SJC08 (zh_cn)","ploxxy (uk_ua, bugfixes)","Fiz-Victor (bugfixes)","co-91 (ja_jp)","JustALittleWolf (#118, \
  #123, #131-2)","SmajloSlovakian (#139-141)","LucunJi (#152, #154)","DylanKeir (#190)","Nooiee (ko_kr/#193)","suoyukii (zh_cn/#203)","demorogabrtz \
  (pt_br/#204)","NotRyken (#215)","Nukecraft5419 (it_it/#219)","Fabian42 (#221)","radioactive-exe (#224)","VidTu (#225)","collin-b1 (#229-30),FateARE77 (ru_ru)"
mod.license=LGPLv3
mod.source=mrbuilder1961/ChatPatches
mod.curseforge=560042
mod.modrinth=MOqt4Z5n

# vcs is automatically set to the most recent fabric version

# Plugin versions (intentionally without dots so they can be declared here)
# /- https://kotlinlang.org/docs/releases.html
kotlin=2.2.0
# /- https://maven.kikugie.dev/#/snapshots/dev/kikugie/stonecutter
stonecutter=0.7+
mdg=_
#lexMdg=_ # if the mdg plugins are diff between lex and neo
# /- https://github.com/isxander/modstitch-stonecutter-template/blob/master/build.gradle.kts#L2
modstitch=0.5.14-unstable
# /- (in the future will be integrated into modstitch, doesn't work atm) https://github.com/modmuss50/mod-publish-plugin?tab=readme-ov-file#basic-usage
mpp=0.8.4

# Fabric specific dependencies - https://fabricmc.net/develop
fabric.loader=0.16.14
# Neoforge specific dependencies
neo.loader=20.2.93
# Legacy forge specific dependencies
forge.loader=_

# Publishing metadata - phase is specified in the version (alpha | beta) and defaults to stable
# /- temporarily disabled neoforge
loaders=fabric
targets=1.20.1,1.20.2,1.20.4,1.20.6,1.21.1,1.21.4,1.21.5,1.21.6,1.21.8
required=fabric-api,yacl
optionals=modmenu,no-chat-reports
incompatibles=
embedded=