org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# /- should work now with Modstitch (and Stonecutter..?) 0.7+
org.gradle.configuration-cache=true

# Update Gradle wrapper with `./gradlew wrapper --gradle-version latest`

# Mod properties
mod.name=Chat Patches
mod.id=chatpatches
mod.group=dev.obro1961
mod.version=8.0-alpha.8
mod.author=OBro1961
mod.desc=A versatile client-side chat mod that makes the chat more useful and customizable! \
  Check out the GitHub page for more info, and join the Discord at https://discord.gg/3MqBvNEyMz!
mod.credits=FITFC (pt_br),Calvineries (fr_fr),SJC08 (zh_cn),ploxxy (uk_ua + bugfixes),Fiz-Victor (bugfixes),co-91 (ja_jp),JustALittleWolf (#118 #123 #131-2),\
  SmajloSlovakian (#139-141),LucunJi (#152 #154),DylanKeir (#190),Nooiee (ko_kr/#193),suoyukii (zh_cn/#203),demorogabrtz (pt_br/#204),NotRyken (#215),\
  Nukecraft5419 (it_it/#219),Fabian42 (#221),radioactive-exe (#224),VidTu (#225),collin-b1 (#229-30),FateARE77 (ru_ru/#234),layou233 (zh_cn/#255)
mod.license=LGPLv3
mod.source=mrbuilder1961/ChatPatches
mod.curseforge=560042
mod.modrinth=MOqt4Z5n

# Plugin versions (intentionally without dots so they can be declared here)
# /- https://kotlinlang.org/docs/releases.html
kotlin=2.3.0
# /- https://maven.kikugie.dev/#/snapshots/dev/kikugie/stonecutter
stonecutter=0.8.1
mdg=_
#lexMdg=_ # if the mdg plugins are diff between lex and neo
# /- https://github.com/isxander/modstitch-stonecutter-template/blob/master/build.gradle.kts#L2
modstitch=0.8.4
loom=1.14-SNAPSHOT
# /- (in the future will be integrated into modstitch, doesn't work atm) https://github.com/modmuss50/mod-publish-plugin?tab=readme-ov-file#basic-usage
mpp=1.1.0

# /- Fabric specific dependencies - https://fabricmc.net/develop
fabric.loader=0.18.4
# /- Neoforge specific dependencies
neo.loader=20.2.93
# /- Legacy forge specific dependencies
forge.loader=_

# Publishing metadata - phase is specified in the version (alpha | beta) and defaults to stable
# /- temporarily disabled neoforge
loaders=fabric
targets=1.20.1,1.20.2,1.20.4,1.20.6,1.21.1,1.21.4,1.21.5,1.21.6,1.21.8,1.21.10,1.21.11
required=fabric-api,yacl
optionals=modmenu,no-chat-reports
# warns: "conflicts" <-> fabric, "discouraged" <-> neo [NOT supported on hosting sites]
# /- crashes: "breaks" <-> fabric, "incompatible" <-> neo [supported on hosting sites]
incompatibles=morechathistory
embedded=