org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# /- should work now with Modstitch (and Stonecutter..?) 0.7+
org.gradle.configuration-cache=true

# Update Gradle wrapper with `./gradlew wrapper --gradle-version latest`

# Mod properties
mod.name=Chat Patches
mod.id=chatpatches
mod.group=dev.obro1961
mod.version=8.0-beta.1
mod.author=OBro1961
mod.desc=A versatile client-side chat mod that makes the chat more useful and customizable! \
  Check out the GitHub page for more info, and join the Discord at https://discord.gg/3MqBvNEyMz!
mod.credits=FITFC (pt_br),Calvineries (fr_fr),SJC08 (zh_cn),ploxxy (uk_ua + bugfixes),Fiz-Victor (bugfixes),co-91 (ja_jp),JustALittleWolf (#118 #123 #131-2),\
  SmajloSlovakian (#139-141),LucunJi (#152 #154),arkosammy12 (#180),DylanKeir (#190),Nooiee (og. ko_kr/#193),suoyukii (zh_cn/#203),demorogabrtz (pt_br/#204),\
  NotRyken (#215),Nukecraft5419 (it_it/#219),Fabian42 (#221),radioactive-exe (#224),VidTu (#225),collin-b1 (#229-30),FateARE77 (ru_ru/#234),SkyNotTheLimit (#252),\
  layou233 (zh_cn/#255),Fourmisain (#285 #297),SirMonkeyBoy (#310),ettip (new ko_kr/#317),ADevnin (new ru_ru/#333),NineOfGaming (#339)
mod.license=LGPLv3
mod.source=mrbuilder1961/ChatPatches
mod.curseforge=560042
mod.modrinth=MOqt4Z5n

# Plugin versions
# /- https://maven.kikugie.dev/#/snapshots/dev/kikugie/fletching-table-two
plugin.fletching-table=0.1.0-alpha.23
# /- https://github.com/google/ksp/releases
plugin.ksp=2.3.9
# /- https://kotlinlang.org/docs/releases.html
plugin.kotlin=2.4.0
# /- https://github.com/isXander/modstitch-toolkit/tree/main#tools
plugin.mtk.manifests=0.1.5
# /- https://github.com/modmuss50/mod-publish-plugin?tab=readme-ov-file#basic-usage
plugin.mod-publish-plugin=2.2.0
# /- https://stonecutter.kikugie.dev/blog/changes/
plugin.stonecutter=0.9.7
# /- https://github.com/isxander/modstitch-stonecutter-template/blob/master/build.gradle.kts#L2
plugin.modstitch=0.8.5

# /- Fabric specific dependencies - https://fabricmc.net/develop
fabric.loom=1.17-SNAPSHOT
fabric.loader=0.19.5
# /- Neoforge specific dependencies
#neo.mod-dev-gradle=_
#neo.loader=20.2.93
# /- Legacy forge specific dependencies
#forge.mod-dev-gradle=_
#forge.loader=_

# Publishing metadata - phase is specified in the version (alpha | beta) and defaults to stable
loaders=fabric
targets=1.20.1,1.21.1,1.21.11,26.1.2,26.2,26.3
required=fabric-api,yacl
optionals=modmenu,no-chat-reports
# warns: "conflicts" <-> fabric, "discouraged" <-> neo [NOT supported on hosting sites]
# /- crashes: "breaks" <-> fabric, "incompatible" <-> neo [supported on hosting sites]
incompatibles=morechathistory
embedded=