modstitch.platform=fabric-loom-remap

# /- Specifies the versions this subproject is compatible with; used by metadata files
# |- Affects the output build's compatibility with other dependencies
#mod.range.metadata=1.21.5
# /- Specifies the versions this subproject is compatible with; used by MPP
# |- Affects the versions created on CF and MR and how they are marked
# |- Must be in Maven format; see modstitch-toolkit/manifest#versionRange()
# |- https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
#mod.range.publishing=[1.21.5]

# https://fabricmc.net/develop
fabric.api=0.128.2

# https://parchmentmc.org/docs/getting-started
dep.parchment=2025.06.15
# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.8.2+1.21.5
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=14.0.2