modstitch.platform=fabric-loom

# todo the goal is to merge these together because they represent the same data:
#  what version(s) are compatible with this release. depends heavily on MPP#116 tho
# https://github.com/modmuss50/mod-publish-plugin/issues/116

# /- Specifies the versions this subproject is compatible with; used by metadata files
# |- Affects the output build's compatibility with other dependencies
mod.range.metadata=~26.2
# /- Specifies the versions this subproject is compatible with; used by MPP
# |- Affects the versions created on CF and MR and how they are marked
# |- Must be in Maven format; see modstitch-toolkit/manifest#versionRange()
# |- https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
mod.range.publishing=[26.2,26.3)
# /- When specified, automatically applies a dependency constraint to enforce the current fabric.api version
# |- Prefix with ! to disable this functionality
#mod.nonReleaseComponent=rc-2
# /- Overrides mod.range
#mod.targets=26.2-rc-2

# https://fabricmc.net/develop
fabric.api=0.153.0

# https://modrinth.com/mod/yacl/versions?l=fabric
#TODO 3.9.5 AWAITING VERIFICATION FROM MAVEN VIA XANDER
dep.yacl=3.9.4+26.2
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=20.0.0-beta.4