modstitch.platform=fabric-loom

# /- stonecutter: ~26.2
mod.range=~26.2
# /- when specified, automatically applies a dependency constraint to enforce the current fabric.api version - prefix with ! to disable this
#mod.nonReleaseComponent=rc-2
#mod.targets=26.2-rc-2

# https://fabricmc.net/develop
fabric.api=0.152.2

# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.9.4+26.2
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=20.0.0-beta.2