modstitch.platform=fabric-loom

# /- stonecutter: ~26.2
mod.range=>26.1
mod.nonReleaseComponent=snapshot-6
mod.versions=26.2
mod.overrides=this doesnt do anything on its own it's just an exists() check but it's overriding yacl's old fapi vers

# https://fabricmc.net/develop
fabric.api=0.148.2

# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.9.3+26.2
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=19.0.0-alpha.1