modstitch.platform=fabric-loom-remap

#mod.range=1.21.6

# https://fabricmc.net/develop
fabric.api=0.128.2

# https://parchmentmc.org/docs/getting-started
dep.parchment=2025.06.29
# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.7.1+1.21.6
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=15.0.0