modstitch.platform=loom

mod.range=[1.21.2,1.21.3,1.21.4]

# https://fabricmc.net/develop
fabric.api=0.119.3

# https://parchmentmc.org/docs/getting-started
dep.parchment=2025.03.23
# https://placeholders.pb4.eu/dev/getting-started/
#dep.placeholder=2.2.1+1.20.2
# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.7.1+1.21.4
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=13.0.3