modstitch.platform=loom

# https://fabricmc.net/develop
fabric.api=0.91.6

# https://parchmentmc.org/docs/getting-started
deps.parchment=2023.12.10
# https://modrinth.com/mod/yacl/versions?l=fabric
# /- 1.20.2 yacl is weird and has a different maven thing ToT
deps.yacl=3.3.0-beta.1+1.20.2
# https://modrinth.com/mod/modmenu/versions?l=fabric
deps.modmenu=8.0.1