modstitch.platform=fabric-loom-remap

mod.range=1.21.7,1.21.8

# https://fabricmc.net/develop
fabric.api=0.136.1

# https://parchmentmc.org/docs/getting-started
dep.parchment=2025.07.20
# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.8.2+1.21.6
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=15.0.0