modstitch.platform=loom

mod.range=1.21.7,1.21.8

# https://fabricmc.net/develop
fabric.api=0.133.0

# https://parchmentmc.org/docs/getting-started
dep.parchment=2025.07.20
# https://placeholders.pb4.eu/dev/getting-started/
dep.placeholder=2.7.2+1.21.8
# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.7.1+1.21.6
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=15.0.0