modstitch.platform=fabric-loom-remap

# /- Specifies the versions this subproject is compatible with
# |- Used as-is* by MPP for publishing on CF + MR, and parsed by
#    manifests#mavenRange() for artifact metadata (fabric.mod.json, neoforge.mods.toml)
# |- Must be in Maven format: https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
# |- Alternatively, you can write a list of versions to use explicitly, instead of a range
# |- If this property is not specified, defaults to the project's version *only*
#mod.range=[1.21.11]

# https://fabricmc.net/develop
fabric.api=0.141.4

# https://parchmentmc.org/docs/getting-started
dep.parchment=2025.12.20
# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.8.2+1.21.11
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=17.0.0