modstitch.platform=loom

mod.range=1.21.11

# https://fabricmc.net/develop
fabric.api=0.140.0

# https://parchmentmc.org/docs/getting-started
#dep.parchment=2025.10.12
# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.8.1+1.21.11
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=17.0.0-alpha.1