modstitch.platform=loom

mod.range=[1.21,1.21.1]

# https://fabricmc.net/develop
fabric.api=0.116.4

# https://parchmentmc.org/docs/getting-started
deps.parchment=2024.11.17
# https://placeholders.pb4.eu/dev/getting-started/
#deps.placeholder=2.2.1+1.20.2
# https://modrinth.com/mod/yacl/versions?l=fabric
deps.yacl=3.7.1+1.21.1
# https://modrinth.com/mod/modmenu/versions?l=fabric
deps.modmenu=11.0.3