modstitch.platform=fabric-loom

# /- Specifies the versions this subproject is compatible with; used by metadata files
# |- Affects the output build's compatibility with other dependencies
mod.range.metadata=~26.1
# /- Specifies the versions this subproject is compatible with; used by MPP
# |- Affects the versions created on CF and MR and how they are marked
# |- Must be in Maven format; see modstitch-toolkit/manifest#versionRange()
# |- https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
mod.range.publishing=[26.1,26.1.2]

# https://fabricmc.net/develop
fabric.api=0.153.0

# https://modrinth.com/mod/yacl/versions?l=fabric
#TODO 3.9.5 AWAITING VERIFICATION FROM MAVEN VIA XANDER
dep.yacl=3.9.4+26.1
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=18.0.0-beta.1