modstitch.platform=fabric-loom

# /- Specifies the versions this subproject is compatible with
# |- Used as-is* by MPP for publishing on CF + MR, and parsed by
#    manifests#mavenRange() for artifact metadata (fabric.mod.json, neoforge.mods.toml)
# |- Must be in Maven format: https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
# |- Alternatively, you can write a list of versions to use explicitly, instead of a range
# |- If this property is not specified, defaults to the project's version *only*
mod.range=[26.1,26.1.2]
# /- When specified, overrides `mod.range` for artifact metadata specifically
# |- Should hopefully be rendered obsolete soon via the implementation of MPP#116 (prepub)
mod.metadata=~26.1

# https://fabricmc.net/develop
fabric.api=0.155.2

# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.9.6+26.1
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=18.0.0