modstitch.platform=loom

mod.range=[1.20.3,1.20.4]

# https://fabricmc.net/develop
fabric.api=0.97.2

# https://parchmentmc.org/docs/getting-started
dep.parchment=2024.04.14
# https://placeholders.pb4.eu/dev/getting-started/
#dep.placeholder=2.2.1+1.20.2
# https://modrinth.com/mod/yacl/versions?l=fabric
dep.yacl=3.6.6+1.20.4
# https://modrinth.com/mod/modmenu/versions?l=fabric
dep.modmenu=9.2.0