modstitch.platform=loom

mod.range=[1.20.5,1.20.6]

# https://fabricmc.net/develop
fabric.api=0.97.3

# https://parchmentmc.org/docs/getting-started
deps.parchment=2024.06.16
# https://placeholders.pb4.eu/dev/getting-started/
#deps.placeholder=
# https://modrinth.com/mod/yacl/versions?l=fabric
#todo make yacl use the mc vers and loader instead of explicitly specifying
deps.yacl=3.6.6+1.20.6
# https://modrinth.com/mod/modmenu/versions?l=fabric
deps.modmenu=10.0.0