# Automatically builds the project and runs any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defense
# against bad commits.

name: build
on:
  # Don't build if only text-based files were changed.
  # Prevents waiting for unnecessary checks/actions
  push:
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - '.gitignore'

jobs:
  build:
    runs-on: 'ubuntu-latest' # Windows was failing for no reason and Stonecutter slows it down anyway
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew collectAll --stacktrace

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            build/libs/
            build/devlibs/